class feature:
    def __init__(self, name: str) -> None: ...
    def __enter__(self) -> "feature": ...
    def __exit__(self, *a: object) -> None: ...
    def __call__(self, fn: object) -> object: ...

target = feature
